### ISSUE TITLE
/invrole disconnect doesn't work

### ISSUE THREAD

**Issue by jesustorresdev** [wow13524/invite-role-bot#1]
Any /invrole disconnect "url" fails with the next error:

~~~
The invite https://discord.gg/%7Binvite_code%7D is not connected to any roles.
~~~

I guess, it is because in this line:

[modules/invite_role_bot/commands/invrole.py#L128](https://github.com/wow13524/invite-role-bot/blob/dcb8b1e633c8299e416b86f3e6dd8d3a55839bc8/modules/invite_role_bot/commands/invrole.py#L128)

the f-string prefix is missing when assigning the string "https://discord.gg/{invite_code}" to value.

**Comment by wow13524** [comment]
Thanks for pointing that out, it was an oversight on my part and should be fixed now.
