### ISSUE TITLE
requirements.txt needs to specify typeguard version

### ISSUE THREAD

**Issue by pcjcos** [wow13524/invite-role-bot#4]
With version 3.0 typeguard now no longer supports the 3 parameter check_type() used in modubot, either modubot needs updated to support the 2 parameter check_type() or requirements.txt should specify `typeguard == 2.13.3`

**Comment by wow13524** [comment]
Thanks for letting me know, I’ve enforced version 2.13.3 for typeguard in requirements.txt.
